apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: shelfshare-postgres
  namespace: shelfshare-localprod
spec:
  interval: 10m
  chartRef:
    kind: OCIRepository
    name: bitnami-postgresql
    namespace: shelfshare-localprod
  valuesFrom:
    - kind: Secret
      name: shelfshare-postgres-values
      valuesKey: values.yaml
