apiVersion: v1
kind: Service
metadata:
    name: books-service
    namespace: shelfshare-localprod
    labels:
        app: books-service
spec:
    type: NodePort
    selector:
        app: books-service
    ports:
        - name: http
          port: 8080
          targetPort: 8080
          nodePort: 30080
