apiVersion: apps/v1
kind: Deployment
metadata:
    name: books-service
    namespace: shelfshare-localprod
    labels:
        app: books-service
spec:
    replicas: 1
    selector:
        matchLabels:
            app: books-service
    template:
        metadata:
            labels:
                app: books-service
        spec:
            containers:
                - name: books-service
                  image: books-service:latest
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 8080
                  envFrom:
                      - configMapRef:
                            name: shelfshare-app-config
                      - secretRef:
                            name: shelfshare-app-secrets
            restartPolicy: Always
