apiVersion: v1
kind: Service
metadata:
    name: envoy
    namespace: shelfshare-localprod
spec:
    selector:
        app: postgres-envoy
    ports:
        - name: postgres-tls
          port: 15432
          targetPort: 15432
          protocol: TCP
